### PR TITLE
09 -- Journal, Week 2

### PR DESCRIPTION
**Pull request by rosalsm**
- **Yak Shaving**
  - [x] Create or update the following _WIP Files_:
    - [x] in `USERNAME.github.io` under branch `journal-week-2` (`USERNAME.github.io:journal-week-2`)
      - [x] `journal-week-2.md` (or your already descriptive name)
  - [x] Add comments to your _WIP Issue_ with links to your PRs in:
    - [x] `USERNAME.github.io` from `journal-week-2` into `master`
- **Journal, Week 2**
  - [x] Rough that draft!
  - [x] :+1: x2 for me...
  - [x] :+1: x2 for you... (with links!)
  - Park those extra ideas for later...

### CODE REVIEW

**Comment by Ricecoder** [comment]
:+1: Good job! I too have to fight frustration so it doesn't stop me from finishing my assignments.

**Comment by cmauban** [comment]
I feel the same way... I definitely need to remember to take baby steps too! :+1:

**Comment by cmauban** [comment]
I feel the same way... I definitely need to remember to take baby steps too! :+1:

**Comment by jeffworley** [comment]
Great self reflection Rosa!  I like how you wove that with an overview of what we have been covering together. :+1:

**Comment by rosalsm** [comment]
https://github.com/TIY-Durham/2015-FALL-FEE/issues/203

**Pull request merged**
