### PR TITLE
Journal, tutorial and source week 5

### PR DESCRIPTION
**Pull request by rosalsm**

### CODE REVIEW

**Comment by s4dmw** [comment]
journal:  good topic, i feel like API knowledge is going to be huge for us :+1: 

resource: great site! i definitely need to spend more time on it...if i only had more time...  :+1: 

tutorial: looks good but covering that much material could turn in to a long tutorial. maybe covering just one or two of those in depth might work better. :+1:

**Comment by jeremyrist** [comment]
:+1: Looks great! I second David on the tutorial thing, might wanna pick just one

**Comment by drumslayert** [comment]
Some good info, but remember your intention should be to walk us through some steps on how to actually do or apply these things. You may want to narrow it down and give us some steps to follow as if we don't know anything about how to apply them. I think your off to a good start. :+1:

**Comment by cmauban** [comment]
Nice tutorial on CSS selectors! Maybe for your next draft, show more examples of how and when they're used! :+1:

**Pull request merged**
