### PR TITLE
final tutorial-week-4.md

### PR DESCRIPTION
**Pull request by rosalsm**

### CODE REVIEW

**Comment by ericksonk** [comment]
Very informative and helped clarify some things for me, good work :+1:

**Comment by Ricecoder** [comment]
Good job! I like how in depth your tutorial is. Maybe next week you can do one on accessing the DOM with jQuery. :+1:

**Comment by boshnivolo** [comment]
This was really helpful! :+1:

**Comment by drumslayert** [comment]
Very informative Rosa! :+1:  I'll probably be referencing this again in the future.

**Comment by karjac14** [comment]
Very profound tutorial to have foundation in concept of the DOM! :+1:

**Pull request merged**
